#include <cstdio>
#include <fstream>
#include <set>
#include <stdexcept>

#include "exporters.hpp"
#include "flatten.hpp"

namespace s2s {

namespace {

// Model mm, Z-up -> OBJ meters, Y-up.
Vec3 to_obj(Vec3 p) { return {p.x / 1000, p.z / 1000, -p.y / 1000}; }

std::string obj_name(std::string s) {
    for (char& c : s)
        if (c == ' ') c = '_';
    return s;
}

}  // namespace

void write_obj(const Scene& scene, const std::string& path, bool includeHidden) {
    const std::string base = path.size() > 4 && path.substr(path.size() - 4) == ".obj" ? path.substr(0, path.size() - 4) : path;
    const std::string mtlPath = base + ".mtl";
    const std::string mtlFile = mtlPath.substr(mtlPath.find_last_of("/\\") + 1);

    std::ofstream obj(path), mtl(mtlPath);
    if (!obj || !mtl) throw std::runtime_error("cannot write " + path);

    mtl << "newmtl Default\nKd 0.92 0.91 0.88\nd 1\n\n";
    for (const Material& m : scene.materials)
        mtl << "newmtl " << obj_name(m.name) << "\nKd " << m.r / 255.0 << " " << m.g / 255.0 << " " << m.b / 255.0
            << "\nd " << m.alpha << "\n\n";

    obj << "# Generated by housegen (Scan-to-SketchUp preview)\nmtllib " << mtlFile << "\n";
    size_t next = 1;
    char buf[96];
    auto vertex = [&](Vec3 p) {
        Vec3 o = to_obj(p);
        std::snprintf(buf, sizeof buf, "v %.5f %.5f %.5f\n", o.x, o.y, o.z);
        obj << buf;
        return next++;
    };
    for (const FlatPart& part : flatten(scene, includeHidden)) {
        obj << "g " << obj_name(part.path) << "\nusemtl " << (part.material.empty() ? "Default" : obj_name(part.material))
            << "\n";
        for (const Triangle& t : part.triangles) {
            size_t a = vertex(t[0]), b = vertex(t[1]), c = vertex(t[2]);
            obj << "f " << a << " " << b << " " << c << "\n";
        }
        for (const auto& line : part.lines) {
            std::string l = "l";
            for (Vec3 p : line) l += " " + std::to_string(vertex(p));
            obj << l << "\n";
        }
    }
}

}  // namespace s2s
